version: "3"
services:
  vpn:
    image: ghcr.io/bubuntux/nordvpn
    cap_add:
      - NET_ADMIN
      - NET_RAW
    environment:
      - TOKEN=f6f2bb45...          # Required NordVPN token
      - CONNECT=United_States      # Specify the country
      - TECHNOLOGY=NordLynx        # Use NordLynx for better performance
      - NETWORK=192.168.1.0/24     # Allow access from the LAN
    ports:
      - "5000:5000"                # Expose port 5000 to the LAN and internet
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=1
    networks:
      - custom_net
    privileged: true

  webamon:
    build: ./Sandbox
    cap_add:
      - NET_ADMIN
      - NET_RAW
    depends_on:
      - vpn
    networks:
      - custom_net
    privileged: true
    ports:
      - "5001:5000"  # Optional, if direct host access is required

networks:
  custom_net:
    driver: bridge
